version: "3.8"

networks:
    group_test:
        name: group_test
        driver: bridge

services:
    python_admin:
        build: .
        container_name: python_admin
        volumes:
            - .:/usr/src/app
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_TOPIC=test
        depends_on: 
            - kafka
        networks: 
            - group_test
    zookeeper:
        image: 'docker.io/bitnami/zookeeper:3-debian-10'
        container_name: zookeeper
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - group_test
    kafka:
        image: 'docker.io/bitnami/kafka:2-debian-10'
        container_name: kafka
        ports:
            - '9092:9092'
        environment: 
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        networks:
            - group_test