version: "3.5"

networks: 
    python_app:
        name: python_app
        driver: bridge

services:
    python_app:
        build: ./app
        container_name: python_app
        volumes:
            - ./app:/usr/src/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_DB=0
            - CASSANDRA_HOST=cassandra
            - CASSANDRA_PORT=9042
            - CASSANDRA_USER=cassandra
            - CASSANDRA_PASSWORD=cassandra
            - CASSANDRA_KEYSPACE=student
            - KAFKA_HOST=kafka
            - KAFKA_USER=kafka
            - KAFKA_PASSWORD=kafka
            - KAFKA_GROUPID=mygroup
            - KAFKA_TOPIC=test
        depends_on: 
            - redis
            - cassandra
            - kafka
        networks:
            - python_app
    redis:
        image: redis:alpine
        container_name: redis
        ports: 
            - '6379:6379'
        networks:
            - python_app
    cassandra:
        image: 'bitnami/cassandra:3-debian-10'
        container_name: cassandra
        ports:
            - '7000:7000'
            - '7199:7199'
            - '9042:9042'
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        networks:
            - python_app
    zookeeper:
        container_name: zookeeper
        image: 'docker.io/bitnami/zookeeper:3-debian-10'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - python_app
    kafka:
        container_name: kafka
        image: 'docker.io/bitnami/kafka:2-debian-10'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        networks:
            - python_app
