version: "3.8"

networks:
    group_test:
        name: group_test
        driver: bridge

services:
    python_consumer_1:
        build: .
        container_name: python_consumer_1
        volumes:
            - .:/usr/src/app
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_GROUPID=group1
            - KAFKA_TOPIC=test
        networks: 
            - group_test
    python_consumer_2:
        build: .
        container_name: python_consumer_2
        volumes:
            - .:/usr/src/app
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_GROUPID=group1
            - KAFKA_TOPIC=test
        networks: 
            - group_test