version: '3.4'

services:
    node:
        build: 
            context: ./back_distr/App
            target: development
        image: node:dev
        environment: 
            - EXPRESSPORT=3000
            - REDISHOST=redis
            - REDISPORT=6379
        ports: 
            - '3000:3000'
        volumes: 
            - ./back_distr/App:/code
    mock:
        build: 
            context: ./back_distr/Mock
            target: development
        image: node:dev
        environment: 
            - REDISHOST=redis
            - REDISPORT=6379
        volumes: 
            - ./back_distr/Mock:/code
    redis:
        image: redis:alpine
    vue:
        build:
            context: ./front
            target: development
        image: front:dev
        environment: 
            - API_URL=http://localhost:3000/
        ports:
            - '8080:8080'
        volumes:
            - ./front:/code
        
